### ISSUE TITLE
tachyon.min.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. 

### ISSUE THREAD

**Issue by danilichti** [weebney/tachyon#20]
tachyon.min.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

<img width="611" alt="CleanShot 2023-01-06 at 12 16 42" src="https://user-images.githubusercontent.com/73495201/211001893-6f36c39c-8c58-4768-bebc-024bc9ac9876.png">

**Comment by cowtoolz** [comment]
Good catch @danilichti, should be fixed now.

**Comment by danilichti** [comment]
Great. 👌🏼
Nachricht von weebney ***@***.***> am 6. Jän. 2023, 16:51 +0100:
