### ISSUE TITLE
Code golf

### ISSUE THREAD

**Issue by ziadkh0** [weebney/tachyon#24]
Replacing
https://github.com/weebney/tachyon/blob/a4d6c56f79a889839f5dea68485f1bf34a9b8111/tachyon/tachyon.js#L38-L42
With
```js
 if (whitelistEnabled == onList) { 
   addListenersToElement(); 
 }
```

Will reduce the minifyed size by a whopping 10 bytes* 😄

*\* I haven't actually tried it to make sure 😅*

**Comment by cowtoolz** [comment]
Can't believe I missed this lol. Good catch.
If you don't mind me asking, how'd you stumble across this project? It's gone from 16 to 46 stars overnight.

**Comment by nikrowell** [comment]
@weebney not sure where else it appeared, but I came across it in yesterday's Frontend Focus email newsletter 
Nice work! 😀
<img width="594" alt="Screen Shot 2023-03-02 at 1 18 56 PM" src="https://user-images.githubusercontent.com/260039/222542719-6eedd2bf-ef6d-4171-b588-c3f07c8c8c25.png">

**Comment by cowtoolz** [comment]
@nikrowell Totally rad. Guess I can finally add an "In the Press" section to my CV

**Comment by ziadkh0** [comment]
> If you don't mind me asking, how'd you stumble across this project? It's gone from 16 to 46 stars overnight.

Same as @nikrowell 😄
