### ISSUE TITLE
I'm getting "TypeError: e.forEach is not a function" thrown in my console

### ISSUE THREAD

**Issue by MSeneadza** [weebney/tachyon#29]
I swapped Tachyon for instant.page on my site and I'm seeing this in my console:

```
Uncaught TypeError: e.forEach is not a function
    at tachyon.min.js:1:593
    at Array.forEach (<anonymous>)
    at MutationObserver.observe.childList (tachyon.min.js:1:580)
```

you can see it live here https://swingtradebot.com/stocks-tagged-as/38592-inverse-etf

**Comment by cowtoolz** [comment]
Are you running tachyon with `<script ... defer>`? I'd appreciate you posting more details when you're able (how you're deploying tachyon and in what cases you're getting the error). I'll look into this tomorrow afternoon. Hope you're enjoying your St. Paddy's day, and glad to see you're also from Atlanta 🙌

**Comment by MSeneadza** [comment]
Oh, how cool that you're also in Atlanta!

Yes, I just copied the script tag from the README (and converted it to HAML) and pasted it into the footer of my site's layout.  (I tried it in the head section and go the same result.)  Here's what I just copied from viewing source on my site:

`<script crossorigin='' defer='defer' integrity='sha384-mWEnITn0upRV8CTm3KnqWW5XKFt7bnWaT6RBKBRIcCPyZx9dxqbAH56ew8NwOTgN' src='https://unpkg.com/tachyonjs@1.1.2/tachyon.min.js' type='module'></script>`
  
It's a Ruby on Rails app & the error seems to appear on every page load on all pages of my site.

**Comment by MSeneadza** [comment]
BTW, I tried it on another Rails app of mine, which has much simpler pages and I get the same results.  You can see that here https://sharesdb.com

**Comment by nikrowell** [comment]
Hey Guys - 
Fun fact - I was just in Atlanta last weekend 😀 and OMG Buttermilk Kitchen!

I had `1.1.0` on a local project and just tried switching over to `1.1.2` and am seeing the same error as @MSeneadza 
Let me know if I can help with troubleshooting in any way.

Cheers!

**Comment by cowtoolz** [comment]
Thanks for the help, guys- accidentally missed a tiny detail pushing out the 1.1.2 release. 1.1.3 includes the relevant fix. Going to start writing a test suite so this doesn't happen again...
