### ISSUE TITLE
Rename Blacklist & Whitelist?

### ISSUE THREAD

**Issue by MSeneadza** [weebney/tachyon#32]
I meant to ask you this several weeks ago when I first found this library.   What are your thoughts on renaming the outdated & culturally awkward blacklist & whitelist?  Over the last couple of years in the Ruby world I've seen libraries replace them with blocklist & allowlist (which are much more obvious & descriptive).  Also see https://www.linkedin.com/pulse/allowlist-blocklist-better-terms-everyone-lets-use-them-rob-black/

**Comment by weebney** [comment]
Good to hear from you again. I've come across this debate before, but haven't given it much thought until now.

On the topic of clarity, the argument that white/blacklist are less obvious or descriptive is kind of silly considering both of these words are well defined and in wide use (even more so in the technical world). I'm not convinced this is a step forward for clarity, but either a lateral step or a step back. Out of curiosity, I searched for both "whitelist" and "allowlist" in Merriam-Webster's online dictionary; whitelist (automatically corrected to "white list") is defined and allowlist is not. Dictionary.com considers whitelist a "High School Level" word (and also leaves allowlist undefined). 

I'm definitely open to discussing this in a social context, though, and I'm open to the change if there's interest in changing it on social grounds. Would love to hear your perspective on the issue in greater detail if you'll share.

I wouldn't expect this to change any time soon, though, considering it would introduce a breaking change so quickly after the release of a new major version (2.0.0, about 3 days ago). If other breaking changes are introduced in the future, that would be the time to change it (i.e. 3.0.0).

**Comment by MSeneadza** [comment]
I just wanted to put that on your radar if it wasn't already.  I know it's not a straight-forward change.   When I first saw this library those terms leapt off the page at me precisely because I'd seen a few Ruby gems put out breaking change releases specifically to rename those terms. 

I don't think it's at all silly to say that white/black-list are obvious to the uninitiated (people new to the software world) and/or non-native English speakers.  

Language evolves over time and dictionaries lag behind on actual usage by real people.  So I wouldn't expect the dictionaries to include the relatively new terms blocklist/block list, denylist/deny list, allowlist/allow list, etc.

In the grand scheme of things using those terms isn't a huge deal & not something I'm willing to spend a lot of time debating.  I'll just add this from [the blacklist wikipedia page](https://en.wikipedia.org/wiki/Blacklist_(computing)#Controversy_over_use_of_the_term) showing that many companies, organizations & projects have made the switch despite what's in the dictionaries (I didn't realize that Rails was so far ahead of the curve until just now):

> In August 2018, [Ruby on Rails](https://en.wikipedia.org/wiki/Ruby_on_Rails) changed all occurrences of "blacklist" and "whitelist" to "restricted list" and "permitted list".[[19]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-19)
> 
> Several companies responded to this controversy in June and July 2020:
> 
> [GitHub](https://en.wikipedia.org/wiki/GitHub) announced that it would replace many "terms that may be offensive to developers in the black community".[[20]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-20)
> [Apple Inc.](https://en.wikipedia.org/wiki/Apple_Inc.) announced at its developer conference that it would be adopting more inclusive technical language and replacing the term "blacklist" with "deny list" and the term "whitelist" with "allow list".[[21]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-21)
> [Linux Foundation](https://en.wikipedia.org/wiki/Linux_Foundation) said it would use neutral language in kernel code and documentation in the future and avoid terms such as "blacklist" and "slave" going forward.[[22]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-22)
> The [Twitter](https://en.wikipedia.org/wiki/Twitter) Engineering team stated its intention to move away from a number of terms, including "blacklist" and "whitelist".[[23]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-23)
> [Red Hat](https://en.wikipedia.org/wiki/Red_Hat) announced that it would make open source more inclusive and avoid these and other terms.[[24]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-24)
> [ZDNet](https://en.wikipedia.org/wiki/ZDNet) reports that the list of technology companies making such decisions "includes Twitter, GitHub, Microsoft, LinkedIn, Ansible, Red Hat, Splunk, Android, Go, MySQL, PHPUnit, Curl, OpenZFS, Rust, JP Morgan, and others."[[25]](https://en.wikipedia.org/wiki/Blacklist_(computing)#cite_note-25)
> 

And from [CNN](https://www.cnn.com/2020/07/06/us/racism-words-phrases-slavery-trnd/index.html):

> Google’s [Chromium](https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral), an open-source browser project, and [Android’s open-source project](https://android-review.googlesource.com/c/platform/frameworks/ml/+/970739) have both encouraged developers to use “blocklist” and “allowlist” instead.

**Comment by MSeneadza** [comment]
Also, if you decide to make the change I’m happy to take a crack at a PR.

**Comment by weebney** [comment]
Sorry, but this is very unlikely to change. After quite a bit of research, I'm convinced this would be a step back for clarity, especially considering at present most users of Tachyon are non-native English speakers (speaking either Chinese or Korean).

**Comment by nikrowell** [comment]
@MSeneadza agree with all your points.
Seems like a pretty trivial change - could even allow both until you're ready to release 3.0.
