### ISSUE TITLE
Unhandled exception on text nodes

### ISSUE THREAD

**Issue by weizman** [weebney/tachyon#33]
1. Visit https://fasterthanlight.net/
2. Open devtools and run `document.body.append('x')`
3. The MObserver will catch the new text node and will try to execute `"tachyon" in t.dataset` but will fail because `dataset` is undefined for text nodes and `in` throws when right-hand is `undefined`

**Comment by cowtoolz** [comment]
Good catch. I'll look into it this afternoon.
