### ISSUE TITLE
Remove var usage

### ISSUE THREAD

**Issue by weizman** [weebney/tachyon#35]
the mini version declares one of the variables using `var` - this is discouraged for many reasons, for example leakage of variables to global object when running in script mode (not module mode)

**Comment by cowtoolz** [comment]
Interesting. I'm obviously not creating `tachyon.min.js` by hand, but I do agree it's strange that [uglify](https://github.com/mishoo/UglifyJS) would do this. Might look into swapping it out for another minifier, but for now it hasn't created any unexpected behavior. As you know, this is only intended to run as a module (at least for now), so I don't know if this is really that big of a deal. Definitely weird, though.
