### ISSUE TITLE
 Cannot use 'in' operator 

### ISSUE THREAD

**Issue by homka506** [weebney/tachyon#37]
Hello, I added a script to the page, but it does not work, it gives errors in the console: 
Uncaught TypeError: Cannot use 'in' operator to search for 'tachyon' in undefined
    at t (tachyon.min.js:1:380)
    at NodeList.forEach (<anonymous>)
    at tachyon.min.js:1:619
    at Array.forEach (<anonymous>)
    at MutationObserver.observe.childList (tachyon.min.js:1:595)

What could be the problem? Thank you

**Comment by cowtoolz** [comment]
Thanks for bringing this to my attention.

1. Can you double check that you're using the correct version? I pushed out a fix for a similar error recently with 2.0.1

2. What website are you getting this error on? How do you have Tachyon installed?

**Comment by homka506** [comment]
Hi, sorry for the delay in reply. Yes, indeed, I had version 2.0.0 connected, thanks.

**Comment by cowtoolz** [comment]
All good, thanks anyway!
