### ISSUE TITLE
Google Tag Manager Invalid HTML, CSS or JavaScript.

### ISSUE THREAD

**Issue by joshysav** [weebney/tachyon#38]
Firstly, thanks a lot! 

Copied the snippet to a new tag in Google Tag Manager.

`<script src="https://unpkg.com/tachyonjs@2.0.1/tachyon.min.js" 
        integrity="sha384-4iJteL1FYnj4Ju83AJvNthpx5gZ1QaXCamXhY3lxhAjTNXUN+NXq5LQV/fXOSRme" type="module" crossorigin defer />`

Seems to be the integrity parameter. Any suggestions?

**Comment by cowtoolz** [comment]
Hey, appreciate it and thanks for making an issue. I haven't seen this one before, does it work fine after removing the `integrity="..."` part?

**Comment by joshysav** [comment]
Thanks for taking the time to reply @weebney. Yes, it works if I remove the integrity flag.

**Comment by cowtoolz** [comment]
Okay, this one is weird. GTM is correct about your tag being invalid, which I didn't notice at first- in standard HTML, `<script>` tags can not be self closing (i.e. `<script />`). As for why removing the integrity hash fixes this, I have no idea, but you should probably correct it for the sake of correctness. Below is the version of the tag I have posted everywhere, and what you should copy paste as a replacement. Still super weird, though.

```
<script src="https://unpkg.com/tachyonjs@2.0.1/tachyon.min.js" integrity="sha384-4iJteL1FYnj4Ju83AJvNthpx5gZ1QaXCamXhY3lxhAjTNXUN+NXq5LQV/fXOSRme" type="module" crossorigin defer></script>
```
