### ISSUE TITLE
Shopify → Tachyon.min.js loads but does not work!

### ISSUE THREAD

**Issue by danilichti** [weebney/tachyon#42]
Newest tachyon script has been implemented: 
![CleanShot 2024-01-03 at 00 17 59](https://github.com/weebney/tachyon/assets/73495201/8b96a89e-189e-40d6-a903-81672884725f)

Checking the Network tab in Chrome, does not show any preloading when hovering over links! 
Test: https://senkels.com

**Comment by cowtoolz** [comment]
The content is actually being downloaded and prerendered, but Chromium doesn't appear to show prerendering network activity in the network tab—just confirmed myself via Wireshark. I've opened [an upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1515601) on the Chromium bugtracker.
